image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: DOSlU041NY0WKjv9njrNqj14CLEzrF4ogZsbvqIXnNLd492oNlQf4dD5yr7TSK/S
  SignClientSecret:
    secure: oR9TMOkkvP/prmXyMT+p6mQhjyw3JDLbuywezBABvXzkvNsdNZgi2yPaHhgaofrb

init:
  - git config --global core.autocrlf input
  
skip_tags: true

build_script:
  - ps: .\Rx.NET\Source\build-new.ps1

test: off
