image: Visual Studio 2015

environment:
  COVERALLS_REPO_TOKEN:
    secure: DOSlU041NY0WKjv9njrNqj14CLEzrF4ogZsbvqIXnNLd492oNlQf4dD5yr7TSK/S
  SignClientSecret:
    secure: oR9TMOkkvP/prmXyMT+p6mQhjyw3JDLbuywezBABvXzkvNsdNZgi2yPaHhgaofrb

build_script:
- ps: .\build.ps1

test: off
